# Generated by Django 4.1 on 2022-08-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application_settings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=50)),
                ('setting_name', models.CharField(max_length=50)),
                ('setting_value', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'myapp',
            },
        ),
    ]
