# Generated by Django 4.1 on 2022-08-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_application_settings_is_enabled'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application_settings',
            table=None,
        ),
    ]
